version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: futpredict_db
    environment:
      POSTGRES_DB: futpredict
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: futpredict_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/futpredict
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: futpredict_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: